// jsonbin-storage-auto.js - 自动生成Bin ID的完整版本
class JsonBinStorage {
    constructor() {
        // 自动生成Bin ID并初始化存储
        this.binId = this.loadBinIdFromStorage() || '未配置';
        this.initialized = false;
        
        // API Keys
        this.readOnlyKey = '$2a$10$AOxCSd1PIW2XUkxQvRpVVeimltcnLXIoOlqvBvFJwlxCihUD2wope';
        this.masterKey = '$2a$10$AOxCSd1PIW2XUkxQvRpVVeimltcnLXIoOlqvBvFJwlxCihUD2wope';
        
        this.baseUrl = 'https://api.jsonbin.io/v3/b';
        this.apiBaseUrl = 'https://api.jsonbin.io/v3';
        
        console.log('🔄 JSONBin存储初始化，当前Bin ID:', this.binId);
    }
    
    /**
     * 从本地存储加载Bin ID
     */
    loadBinIdFromStorage() {
        try {
            return localStorage.getItem('jsonbin_bin_id');
        } catch (error) {
            console.warn('无法访问本地存储:', error);
            return null;
        }
    }
    
    /**
     * 保存Bin ID到本地存储
     */
    saveBinIdToStorage(binId) {
        try {
            localStorage.setItem('jsonbin_bin_id', binId);
            return true;
        } catch (error) {
            console.warn('无法保存到本地存储:', error);
            return false;
        }
    }
    
    /**
     * 检查是否需要创建新的Bin
     */
    async checkAndCreateBinIfNeeded() {
        // 如果已经有Bin ID，验证它是否有效
        if (this.binId && this.binId !== '未配置') {
            const testResult = await this.testConnection();
            if (testResult.connected) {
                console.log('✅ 使用现有Bin ID:', this.binId);
                this.initialized = true;
                return {
                    success: true,
                    message: `使用现有Bin: ${this.binId}`,
                    binId: this.binId,
                    existing: true
                };
            }
            
            console.warn('现有Bin ID无效，将创建新Bin');
        }
        
        // 创建新Bin
        return await this.createAndSetupNewBin();
    }
    
    /**
     * 自动创建和配置新的Bin
     */
    async createAndSetupNewBin() {
        console.log('🔄 正在创建新的JSONBin存储...');
        
        try {
            // 1. 创建新的Bin
            const createResponse = await fetch(`${this.apiBaseUrl}/b`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Master-Key': this.masterKey,
                    'X-Bin-Private': 'false'
                },
                body: JSON.stringify({
                    feedbacks: [],
                    stats: {
                        total: 0,
                        pending: 0,
                        processed: 0,
                        suggestions: 0,
                        problems: 0,
                        complaints: 0,
                        others: 0
                    },
                    system: {
                        created: new Date().toISOString(),
                        lastUpdated: new Date().toISOString(),
                        version: '1.0'
                    },
                    meta: {
                        description: '员工反馈管理系统',
                        version: '1.0',
                        autoGenerated: true
                    }
                })
            });
            
            if (!createResponse.ok) {
                throw new Error(`创建失败: HTTP ${createResponse.status}`);
            }
            
            const createData = await createResponse.json();
            const newBinId = createData.metadata.id;
            
            console.log('✅ 成功创建新Bin:', newBinId);
            
            // 2. 更新Bin ID
            this.binId = newBinId;
            this.saveBinIdToStorage(newBinId);
            
            // 3. 验证创建
            const verifyResponse = await fetch(`${this.baseUrl}/${newBinId}`, {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Access-Key': this.readOnlyKey
                }
            });
            
            if (!verifyResponse.ok) {
                throw new Error('验证Bin创建失败');
            }
            
            const verifyData = await verifyResponse.json();
            console.log('✅ Bin验证成功:', verifyData.record?.meta?.description || '新Bin');
            
            this.initialized = true;
            
            return {
                success: true,
                message: '✅ 新Bin创建并配置成功!',
                binId: newBinId,
                existing: false,
                record: verifyData.record
            };
            
        } catch (error) {
            console.error('❌ 创建Bin失败:', error);
            return {
                success: false,
                message: `创建失败: ${error.message}`,
                binId: null
            };
        }
    }
    
    /**
     * 测试连接
     */
    async testConnection() {
        if (!this.binId || this.binId === '未配置') {
            return {
                connected: false,
                message: '❌ Bin ID未配置'
            };
        }
        
        try {
            const response = await fetch(`${this.baseUrl}/${this.binId}`, {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Access-Key': this.readOnlyKey
                }
            });
            
            if (response.status === 404) {
                return {
                    connected: false,
                    message: `❌ Bin ${this.binId} 不存在`
                };
            }
            
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }
            
            const data = await response.json();
            const count = data.record?.feedbacks?.length || 0;
            
            return {
                connected: true,
                message: `✅ 连接成功 (${count}条反馈)`,
                binId: this.binId,
                feedbackCount: count,
                record: data.record
            };
            
        } catch (error) {
            return {
                connected: false,
                message: `❌ 连接失败: ${error.message}`,
                binId: this.binId
            };
        }
    }
    
    /**
     * 初始化存储系统（自动检测或创建Bin）
     */
    async initialize() {
        if (this.initialized) {
            return {
                success: true,
                message: '存储系统已初始化',
                binId: this.binId
            };
        }
        
        console.log('🔄 初始化JSONBin存储系统...');
        return await this.checkAndCreateBinIfNeeded();
    }
    
    /**
     * 获取所有反馈
     */
    async getFeedbacks() {
        if (!this.initialized) {
            const initResult = await this.initialize();
            if (!initResult.success) {
                console.warn('初始化失败，返回空数组');
                return [];
            }
        }
        
        try {
            const response = await fetch(`${this.baseUrl}/${this.binId}`, {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Access-Key': this.readOnlyKey
                }
            });
            
            if (!response.ok) {
                console.warn('获取失败，返回空数组');
                return [];
            }
            
            const data = await response.json();
            return data.record?.feedbacks || [];
            
        } catch (error) {
            console.error('获取反馈失败:', error);
            return [];
        }
    }
    
    /**
     * 保存反馈
     */
    async saveFeedback(feedbackData) {
        if (!this.initialized) {
            const initResult = await this.initialize();
            if (!initResult.success) {
                return {
                    success: false,
                    message: '存储系统未初始化'
                };
            }
        }
        
        try {
            // 1. 获取当前数据
            const getResponse = await fetch(`${this.baseUrl}/${this.binId}`, {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Access-Key': this.readOnlyKey
                }
            });
            
            if (!getResponse.ok) {
                throw new Error('获取当前数据失败');
            }
            
            const getData = await getResponse.json();
            const record = getData.record;
            
            // 2. 创建新反馈
            const newFeedback = {
                id: 'fb_' + Date.now(),
                employeeName: feedbackData.employeeName || '匿名员工',
                type: feedbackData.type,
                content: feedbackData.content,
                images: feedbackData.images || [],
                status: 'pending',
                timestamp: new Date().toISOString()
            };
            
            // 3. 添加到数组
            if (!record.feedbacks) record.feedbacks = [];
            record.feedbacks.push(newFeedback);
            
            // 4. 更新统计
            if (!record.stats) {
                record.stats = {
                    total: 0,
                    pending: 0,
                    processed: 0,
                    suggestions: 0,
                    problems: 0,
                    complaints: 0,
                    others: 0
                };
            }
            
            record.stats.total = record.feedbacks.length;
            record.stats.pending = record.feedbacks.filter(f => f.status === 'pending').length;
            
            // 根据类型更新统计
            if (newFeedback.type === 'suggestion') record.stats.suggestions++;
            else if (newFeedback.type === 'problem') record.stats.problems++;
            else if (newFeedback.type === 'complaint') record.stats.complaints++;
            else if (newFeedback.type === 'other') record.stats.others++;
            
            // 5. 更新系统信息
            if (!record.system) record.system = {};
            record.system.lastUpdated = new Date().toISOString();
            
            // 6. 保存回云端
            const saveResponse = await fetch(`${this.baseUrl}/${this.binId}`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'X-Master-Key': this.masterKey
                },
                body: JSON.stringify(record)
            });
            
            if (!saveResponse.ok) {
                throw new Error('保存失败: ' + saveResponse.status);
            }
            
            console.log('✅ 反馈保存成功:', newFeedback.id);
            
            return {
                success: true,
                id: newFeedback.id,
                message: '反馈已成功保存到云端',
                binId: this.binId,
                feedback: newFeedback
            };
            
        } catch (error) {
            console.error('保存失败:', error);
            return {
                success: false,
                message: '保存失败: ' + error.message
            };
        }
    }
    
    /**
     * 获取统计
     */
    async getStats() {
        if (!this.initialized) {
            const initResult = await this.initialize();
            if (!initResult.success) {
                return this.getDefaultStats();
            }
        }
        
        try {
            const response = await fetch(`${this.baseUrl}/${this.binId}`, {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Access-Key': this.readOnlyKey
                }
            });
            
            if (!response.ok) {
                return this.getDefaultStats();
            }
            
            const data = await response.json();
            return data.record?.stats || this.getDefaultStats();
            
        } catch (error) {
            console.error('获取统计失败:', error);
            return this.getDefaultStats();
        }
    }
    
    /**
     * 获取默认统计
     */
    getDefaultStats() {
        return {
            total: 0,
            pending: 0,
            processed: 0,
            suggestions: 0,
            problems: 0,
            complaints: 0,
            others: 0
        };
    }
    
    /**
     * 重置存储（创建新的Bin）
     */
    async resetStorage() {
        console.log('🔄 重置存储，创建新Bin...');
        
        // 清除本地存储的Bin ID
        try {
            localStorage.removeItem('jsonbin_bin_id');
        } catch (error) {
            // 忽略错误
        }
        
        // 重置状态
        this.binId = '未配置';
        this.initialized = false;
        
        // 创建新Bin
        return await this.createAndSetupNewBin();
    }
    
    /**
     * 获取存储状态信息
     */
    async getStorageInfo() {
        const connectionStatus = await this.testConnection();
        const stats = await this.getStats();
        
        return {
            binId: this.binId,
            initialized: this.initialized,
            connectionStatus,
            stats,
            localStorageAvailable: this.testLocalStorage()
        };
    }
    
    /**
     * 测试本地存储是否可用
     */
    testLocalStorage() {
        try {
            const testKey = '__storage_test__';
            localStorage.setItem(testKey, testKey);
            localStorage.removeItem(testKey);
            return true;
        } catch (error) {
            return false;
        }
    }
}

// 全局实例
const jsonBinStorage = new JsonBinStorage();

// 辅助函数：一键初始化
async function initializeJsonBinStorage() {
    console.log('🚀 开始初始化JSONBin存储...');
    const result = await jsonBinStorage.initialize();
    
    if (result.success) {
        console.log('✅ JSONBin存储初始化成功!');
        console.log(`📦 Bin ID: ${result.binId}`);
        if (result.existing) {
            console.log('📊 使用现有Bin');
        } else {
            console.log('✨ 创建了新Bin');
        }
    } else {
        console.error('❌ JSONBin存储初始化失败:', result.message);
    }
    
    return result;
}

// 辅助函数：显示存储状态
async function showStorageStatus() {
    const info = await jsonBinStorage.getStorageInfo();
    
    console.group('📊 JSONBin存储状态');
    console.log('Bin ID:', info.binId);
    console.log('初始化状态:', info.initialized ? '✅ 已初始化' : '❌ 未初始化');
    console.log('连接状态:', info.connectionStatus.message);
    console.log('本地存储:', info.localStorageAvailable ? '✅ 可用' : '❌ 不可用');
    console.log('统计信息:', info.stats);
    console.groupEnd();
    
    return info;
}

// 自动初始化（可选，取消注释以启用）
// document.addEventListener('DOMContentLoaded', async () => {
//     // 等待页面加载完成后自动初始化
//     setTimeout(async () => {
//         await initializeJsonBinStorage();
//         await showStorageStatus();
//     }, 1000);
// });